version: '3.8'

services:
  # Fedora test environment
  metisara-fedora:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: fedora:latest
    container_name: metisara-fedora-test
    volumes:
      # Mount current directory for live development
      - .:/home/testuser/metisara-dev:ro
      # Mount workspace for testing (persistent between runs)
      - metisara-workspace-fedora:/home/testuser/metisara/workspace
    environment:
      - METISARA_ENV=development
      - PYTHONPATH=/home/testuser/metisara/src
    working_dir: /home/testuser/metisara
    stdin_open: true
    tty: true
    command: /bin/bash

  # Alpine test environment (lightweight)
  metisara-alpine:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: alpine:latest
    container_name: metisara-alpine-test
    volumes:
      - .:/home/testuser/metisara-dev:ro
      - metisara-workspace-alpine:/home/testuser/metisara/workspace
    environment:
      - METISARA_ENV=development
      - PYTHONPATH=/home/testuser/metisara/src
    working_dir: /home/testuser/metisara
    stdin_open: true
    tty: true
    command: /bin/bash

  # Test environment with sample data
  metisara-test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: fedora:latest
    container_name: metisara-full-test
    volumes:
      - .:/home/testuser/metisara-dev:ro
      - metisara-workspace-test:/home/testuser/metisara/workspace
      # Mount test data
      - ./tests/fixtures:/home/testuser/metisara/test-data:ro
    environment:
      - METISARA_ENV=testing
      - PYTHONPATH=/home/testuser/metisara/src
      # Mock JIRA token for testing
      - JIRA_API_TOKEN=test-token-for-dry-run
    working_dir: /home/testuser/metisara
    stdin_open: true
    tty: true
    command: /bin/bash -c "source venv/bin/activate && echo 'Running test setup...' && make setup && echo 'Test environment ready!' && /bin/bash"

volumes:
  metisara-workspace-fedora:
  metisara-workspace-alpine:
  metisara-workspace-test: